# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Soap Box
email: gestalta@soapboxshibari.com
description: > # this means to ignore newlines until "baseurl:"
  The Soapbox is a regular night of rope and more at Anatomie Studio, London
baseurl: /soapbox # the subpath of your site, e.g. /blog
# baseurl: /soapbox # the subpath of your site, e.g. /blog
url: "http://gestalta.github.io" # the base hostname & protocol for your site
twitter_username: gestalta
github_username:  gestalta

# Build settings
markdown: kramdown
future: true
